### ISSUE TITLE
Add a private method macro

### ISSUE THREAD

**Issue by melix99** [jf2048/gobject#10]
Currently it doesn't seem possible to create a method that is only visible inside the gobject impl. This is needed to e.g. implement private methods that accesses the properties without needing to make them public.

**Comment by jf2048** [comment]
My suggestion would be to do this inside the module:

```rust
impl super::MyObject {
    fn blah(&self) { /* ... */ }
}
```

**Comment by melix99** [comment]
Oh, yeah, that works great!
