### ISSUE TITLE
Names that contain rust keywords break the property macro

### ISSUE THREAD

**Issue by melix99** [jf2048/gobject#12]
I have a `type_` field that I want to expose as a property, but using the property macro I get this error:

```
#[gobject::class(final)]
^^^^^^^^^^^^^^^^^^^^^^^^ expected identifier, found keyword
```

**Comment by jf2048** [comment]
It will add an underscore now to any keywords, but note that `type_` still will conflict with `ObjectExt` if you use it in a non-final class. You'll have to fully qualify it, or rename the getter
