### ISSUE TITLE
Let the user specify if they want a nullable object property or not

### ISSUE THREAD

**Issue by melix99** [jf2048/gobject#13]
Currently it seems that if I use a `RefCell<Option<glib::Object>>` as a property, the macro will generate the relative getter and setter of the type `Option<glib::Object>` instead of what I wanted (just a `glib::Object`). Setting a custom getter and setter does not work because the macro still expects an `Option`. My suggestion is to add a sort of "nullable" macro attribute to let the user decide whether to have a nullable property or not.

**Comment by jf2048** [comment]
I think you want to use `ConstructCell`

**Comment by melix99** [comment]
Oh wow, that's super nice! Thanks for all this amazing work! :)
