### ISSUE TITLE
clone-blockify: Replace expressions based on LineColumn

### ISSUE THREAD

**Issue by jf2048** [jf2048/gobject#15]
Currently the formatting and comments are messed up. Instead of rewriting the whole file, it needs to replace only the region in between `.span().start()` and `.span().end()`

**Comment by Hofer-Julian** [comment]
Maybe this is also useful: https://github.com/fengalin/fix-getters
That was used to ease the transition from `get_property()` to `property()` for `gtk-rs` users.

**Comment by jf2048** [comment]
Hmm, that's a good idea. It's using syn but only replacing based on line and column, not rewriting the whole file
