### ISSUE TITLE
Support non-optional getters for weak refs

### ISSUE THREAD

**Issue by melix99** [jf2048/gobject#16]
I know that weak refs should return an Option ideally, but I have cases where I have e.g. an object A that has a strong ref of B, and the B object that has a weak ref of A, and since I know that B will exist as long as A exists, I just unwrap the A weak reference in B's getter.

**Comment by jf2048** [comment]
This is not going to work with writable properties because you could still manually set the property to `None`. It would be better to make this a read-only property with a custom getter that calls unwrap.

**Comment by jf2048** [comment]
BTW something like `ConstructWeakCell` could be added to make this easier

**Comment by jf2048** [comment]
Added it https://github.com/jf2048/gobject/commit/eb2ae785c93666ea6e92165d910fbb8ddc51c326

**Comment by melix99** [comment]
Tested it, it works great!
