### ISSUE TITLE
`clone-blockify`: Run `cargo fmt` in the end

### ISSUE THREAD

**Issue by Hofer-Julian** [jf2048/gobject#3]
I've noticed that `cargo fmt` still formats after the `clone-blockify` run.
Not a big deal, but maybe `clone-blockify` could do that for you.

**Comment by jf2048** [comment]
It doesn't seem to be possible to run `cargo fmt` on just one file?

**Comment by jf2048** [comment]
I'm kind of leaning towards not automatically formatting at all, that's really a separate step.

**Comment by jf2048** [comment]
I think this is fixed now that the formatting doesn't get messed up anymore
