### ISSUE TITLE
`clone_block` macro: Motivate different order in macro

### ISSUE THREAD

**Issue by Hofer-Julian** [jf2048/gobject#5]
Currently this is the suggested order of arguments for closures with `clone_block` attributes:

1. Cloned values
2. Actual parameters of the final closure

```rust
move |#[strong] refcell, #[strong] obj, extra: &str| {
```

I suggest to reverse this:

1.  Actual parameters of the final closure
2. Cloned values

```rust
move |extra: &str, #[strong] refcell, #[strong] obj| {
```

I like it more since these cloned values are the extra, that will be stripped away afterwards.
People will have to take care that the original parameters fit the expected closure, so that's where there should be their focus

**Comment by jf2048** [comment]
I agree with this although it's only a matter of convention. This will work already, the position of the captures is not important. I think all that needs to be done here is to change clone-blockify to append the captures instead of prepend and update the tests.

**Comment by jf2048** [comment]
clone-blockify will now append captures to the end
