### ISSUE TITLE
`clone-blockify` macro: Preserve default

### ISSUE THREAD

**Issue by Hofer-Julian** [jf2048/gobject#6]
`clone-blockify` currently modifies files like that.

```diff
-        clone!(@weak button => @default-return Continue(false),
-                    move |enable_button| {
+        move |# [weak (or_return Continue (false))] button, enable_button| {
```

I would have expected to preserve the default like this:

```diff
-        clone!(@weak button => @default-return Continue(false),
-                    move |enable_button| {
+        #[default_return Continue (false)] move |# [weak] button, enable_button| {
```

**Comment by jf2048** [comment]
It will do that if there are two or more weak captures. I had it use `or_return` if there is only one weak capture just because it's shorter

**Comment by Hofer-Julian** [comment]
> because it's shorter

That's a fair point. Personally, I find the version using `default_return` also more readable. Not sure if other people feel the same.
