### ISSUE TITLE
Allow having gobject's inner structs with limited visibility

### ISSUE THREAD

**Issue by melix99** [jf2048/gobject#8]
Currently it seems that the gobject structs need to be public, otherwise you get a `crate-private type 'object::imp:Object' in public interface` error. Is it possible to allow at least a `pub(crate)` visibility?

**Comment by melix99** [comment]
Mh, maybe I'm wrong, but I'm pretty sure you can at least set the visiblity of the entire gobject to something different than `pub`, e.g. this is what I'm doing in my app, I'm setting both the imp struct and the gobject itself to `pub(crate)` and it works just fine. But maybe there's a specific problem doing that with this macro?

**Comment by jf2048** [comment]
You can but I didn't add that yet, the visibility of the inner struct always has to match the wrapper type

**Comment by jf2048** [comment]
The wrapper type could always match the visibility of the inner struct, except when it's private then we'll have to force the inner to `pub(super)`

**Comment by jf2048** [comment]
That still has some issues, need to map:

- `pub(self)`, `pub(in self)` → `pub(super)`
- `pub(super)` → `pub(in super::super)`
- `pub(in super:: ...)` → `pub(in super::super:: ...)`

**Comment by jf2048** [comment]
Can you try now after https://github.com/jf2048/gobject/commit/ec97da1b74b2d4c6d7162b6682dd3ef93ceb6e0a and see if that lets you do it?

**Comment by melix99** [comment]
Yes, it works (at least with the `pub(crate)` visibility).
