### ISSUE TITLE
Make gobject macro work without requiring glib in Cargo.toml

### ISSUE THREAD

**Issue by melix99** [jf2048/gobject#9]
I noticed that if I use `#[gobject::class(final)]` in a gtk app, it doesn't compile with this error: `use of undeclared crate or module 'glib'`. I tried importing `gtk::glib` in that module but that didn't change anything, I had to add glib in my `Crate.toml` to fix this. Maybe this can be changed somehow?

**Comment by jf2048** [comment]
I was thinking about this, it can probably be done by strategically placing `use gobject::glib` statements in a few places within the macro
